"""Add unit column to reagent_values table

Revision ID: 0e9084bb5645
Revises: 4e808779618d
Create Date: 2025-10-25 18:37:15.975568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9084bb5645'
down_revision: Union[str, Sequence[str], None] = '4e808779618d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reagent_values', sa.Column('unit', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reagent_values', 'unit')
    # ### end Alembic commands ###
