"""Add reagent, plate_reagent_map, and plate tables

Revision ID: 20452bcac74a
Revises: 
Create Date: 2025-10-25 14:36:18.802506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20452bcac74a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reagent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_reagent_map',
    sa.Column('plate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('reagent_id', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reagent_id'], ['reagent.id'], ),
    sa.PrimaryKeyConstraint('plate_id')
    )
    op.create_table('plate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plate_id'], ['plate_reagent_map.plate_id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['plate_reagent_map.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plate')
    op.drop_table('plate_reagent_map')
    op.drop_table('reagent')
    # ### end Alembic commands ###
