"""Add plate_id and seconds_time_sample to plate table

Revision ID: 4e808779618d
Revises: ac8e5e5f0a9e
Create Date: 2025-10-25 18:16:34.480869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e808779618d'
down_revision: Union[str, Sequence[str], None] = 'ac8e5e5f0a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
