"""Add cell_growth table

Revision ID: 549dc6afa744
Revises: 20452bcac74a
Create Date: 2025-10-25 15:07:57.724979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549dc6afa744'
down_revision: Union[str, Sequence[str], None] = '20452bcac74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_growth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('cell_density', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plate_id'], ['plate_reagent_map.plate_id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['plate_reagent_map.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell_growth')
    # ### end Alembic commands ###
