"""add cache tables for future house literature related organisms and protocol tracking

Revision ID: 8fe0ad5d725d
Revises: 0e9084bb5645
Create Date: 2025-10-26 04:02:26.829105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe0ad5d725d'
down_revision: Union[str, Sequence[str], None] = '0e9084bb5645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_house_literature',
    sa.Column('organisms', sa.String(), nullable=False),
    sa.Column('literature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('organisms')
    )
    op.create_table('protocol_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_organism', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_organisms',
    sa.Column('organism', sa.String(), nullable=False),
    sa.Column('related_organisms', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('organism')
    )
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('reagent_name', sa.String(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol_tracker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol')
    op.drop_table('related_organisms')
    op.drop_table('protocol_tracker')
    op.drop_table('future_house_literature')
    # ### end Alembic commands ###
