"""add time and plate columns to plate model

Revision ID: ac8e5e5f0a9e
Revises: 1976545a548b
Create Date: 2025-10-25 18:10:44.262106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8e5e5f0a9e'
down_revision: Union[str, Sequence[str], None] = '1976545a548b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('plate_id', sa.Integer(), nullable=False))
    op.add_column('plate', sa.Column('seconds_time_sample', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plate', 'seconds_time_sample')
    op.drop_column('plate', 'plate_id')
    # ### end Alembic commands ###
